# Change these first
owner: Krea-University # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Krea Website
    url: https://krea.edu.in
  - name: Krea One ERP
    url: https://oneerp.krea.edu.in
  - name: Krea ERP
    url: https://erp.krea.edu.in
  - name: Krea ERP API
    url: https://api.erp.krea.edu.in/hello
  - name: Krea It Site
    url: https://hostinger.krea.edu.in  
  - name: Krea NMS
    url: https://sc-nms.krea.edu.in
status-website:
  cname: statuspage.krea.edu.in
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.krea.edu.in/_/erp/logo.png
  name: Krea Uptime
  introTitle: Welcome to Krea University Uptime Monitoring
  introMessage: At Krea University, we strive to ensure uninterrupted access to all our web services. This portal provides real-time updates and monitoring of our online platforms, ensuring you stay informed about their availability and performance.
  navbar:
    - title: Status
      href: /
    - title: Our Site
      href: https://tech.krea.edu.in/
i18n:
  footer: Made with by Krea IT Team

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
