# Change these first
owner: Krea-University # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Website
    url: https://krea.edu.in
  - name: One ERP Frontend
    url: https://oneerp.krea.edu.in
  - name: ERP Frontend
    url: https://erp.krea.edu.in
  - name: Main Website Webserver
    url: https://hostinger.krea.edu.in  
  - name: NMS
    url: https://sc-nms.krea.edu.in
  - name: ERP API
    url: https://api.erp.krea.edu.in/heartbeat
status-website:
  cname: statuspage.krea.edu.in
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.krea.edu.in/_/erp/logo.png
  name: Krea Uptime
  introTitle: Welcome to Krea University Uptime Monitoring
  introMessage: At Krea University, we strive to ensure uninterrupted access to all our web services. This portal provides real-time updates and monitoring of our online platforms, ensuring you stay informed about their availability and performance.
  navbar:
    - title: Status
      href: /
    - title: Our Site
      href: https://tech.krea.edu.in/
i18n:
  footer: Made with ❤️ by [Krea IT Team](https://tech.krea.edu.in)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
